[module/taskbar]
type = custom/script
exec = $HOME/.local/share/dwm-pathvoid/polybar/scripts/dwm-taskbar.sh --tail
tail = true

format = <label>
format-foreground = ${colors.fg}
format-background = ${colors.bg}
format-padding = 1

label = %output%

; Color customization
env-DWM_TASKBAR_ACTIVE_COLOR = #eceff4
env-DWM_TASKBAR_INACTIVE_COLOR = #d8dee9
env-DWM_TASKBAR_HIDDEN_COLOR = #4c566a
env-DWM_TASKBAR_ACTIVE_BG = #434c5e
env-DWM_TASKBAR_MAX_TITLE = 25
env-DWM_TASKBAR_FONT = 2
