#!/bin/bash
# Taskbar action handler
# Usage: dwm-taskbar-action <action> <wid>
#   toggle - toggle hide/show
#   close  - close window

action="$1"
wid="$2"
[ -z "$wid" ] && exit 1

case "$action" in
    toggle)
        xprop -root -f _DWM_TOGGLE_HIDE 32x -set _DWM_TOGGLE_HIDE "$wid"
        ;;
    close)
        wmctrl -ic "$wid"
        ;;
esac
